import './globals.css'
// import styles from "./page.module.css";
import { Inter } from "next/font/google";
import { ContextProvider } from '@/app/context/TeamContext';
import Navbar from '@/app/components/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} max-w-[1180px] mx-auto px-4 text-center space-y-8`}>
        <Navbar />
        <main>
          <ContextProvider>
            {children}
          </ContextProvider>
        </main>
        {/* Footer */}
      </body>
    </html>
  )
}
